### ISSUE TITLE
programmatic list creation

### ISSUE THREAD

**Issue by untitaker** [hueyy/mastodon-lists-manager#2]
I am maintaining a "mutuals" list that consists of exactly the people I follow and who also follow me. I also would like to have a list of people who rarely post, so I do not miss their posts, but this is currently too hard to maintain.

Is stuff like this within scope of the project? I am considering building a tool for a start that can maintain the mutuals list for me, and I wonder if I should contribute it here instead of creating a dedicated one.

**Comment by hueyy** [comment]
How would this mutuals list be updated? Right now this tool only runs on an
ad hoc basis (i.e. whenever you run it) - if that's fine, I'm happy for you
to include this tool as a feature here.

**Comment by untitaker** [comment]
> How would this mutuals list be updated? Right now this tool only runs on an
ad hoc basis (i.e. whenever you run it) - if that's fine, I'm happy for you
to include this tool as a feature here.

Yeah I feel like the alternatives (like hosting a service that runs a cron for everybody) would be not worth the effort.

**Comment by untitaker** [comment]
I ended up building a separate service at https://github.com/untitaker/mastodon-list-bot
